stages:
  - linting
  - black

flake8:
  stage: linting
  image: registry.gitlab.com/pipline-components/flake8:latest
  script:
    - pip install flake8-import-order flake8-quotes pep8-naming
    - flake8 --verbose .

black:
  stage: black
  image: python:3.12
  script:
    - pip install black
    - black --config pyproject.toml .
    - black --check .
