stages:
  - test
  - linting
  - black
  - github

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install flake8-bugbear flake8-clean-block flake8-expression-complexity flake8-import-order flake8-quotes pep8-naming flake8-absolute-import flake8-commas flake8-eradicate flake8-comprehensions flake8-fixme flake8-dunder-all flake8-print flake8-type-ignore flake8-comments flake8-use-pathlib flake8-return flake8-builtins
    - flake8 --config .flake8

black:
  stage: black
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --config pyproject.toml --check .

test:
  stage: test
  image: python:3.12
  script:
    - python -m venv $CI_PROJECT_DIR/venv
    - source $CI_PROJECT_DIR/venv/bin/activate
    - pip install -r requirements/prod.txt -r requirements/test.txt
    - cd $CI_PROJECT_DIR/lyceum
    - python manage.py test
    - deactivate
    - rm -rf $CI_PROJECT_DIR/venv