stages:
  - test
  - linting
  - black

before_script:
  - cp .env.example .env

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install flake8-import-order flake8-quotes pep8-naming
    - flake8 --ignore Q000 --verbose .

black:
  stage: black
  image: python:3.12
  script:
    - pip install black
    - black --config pyproject.toml .
    - black --check .

test:
  stage: test
  image: python:3.12
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements/prod.txt -r requirements/dev.txt
    - cd lyceum
    - python manage.py test
    - deactivate
