stages:
  - linting
  - black

flake8:
  stage: linting
  script:
    - pip install flake8-import-order flake8-quotes pep8-naming

black:
  stage: black
  image: python 3.9
  script:
    - pip install black
    - black --config pyproject.toml .
    - black --check .
