# Generated by Django 4.2 on 2024-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Введите текстовое поле обращения',
                        verbose_name='текстовое поле',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='Дата создания',
                        verbose_name='дата создания',
                    ),
                ),
                (
                    'mail',
                    models.EmailField(
                        help_text='Адрес электронной почты',
                        max_length=254,
                        verbose_name='электронный адрес',
                    ),
                ),
            ],
        ),
    ]
