# Generated by Django 4.2 on 2024-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='Дата создания',
                null=True,
                verbose_name='дата создания',
            ),
        ),
    ]
