# Generated by Django 4.2 on 2024-03-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(
                help_text='Укажите имя отправителя. Максимальная длинна - 256 символов.',
                max_length=256,
                null=True,
                verbose_name='имя отправителя',
            ),
        ),
    ]
