# Generated by Django 4.2 on 2024-03-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0003_alter_feedback_options_feedback_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ("name",),
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
            },
        ),
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "ordering": ("user",),
                "verbose_name": "журнал состояния",
                "verbose_name_plural": "журнал состояний",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Укажите имя отправителя. Максимальная длинна - 256 символов.",
                max_length=150,
                null=True,
                verbose_name="имя отправителя",
            ),
        ),
    ]
