# Generated by Django 4.2 on 2024-03-17 08:20

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    sorl.thumbnail.fields.ImageField(
                        upload_to=core.models.item_directory_path,
                        verbose_name='изображение',
                    ),
                ),
                (
                    'birthday',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='дата рождения'
                    ),
                ),
                (
                    'coffee_count',
                    models.IntegerField(
                        default=0, verbose_name='количество выпитого кофе'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'профиль пользователя',
                'verbose_name_plural': 'профили пользователей',
            },
        ),
    ]
