# Generated by Django 4.2 on 2024-03-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Выберите дату своего рождения",
                        null=True,
                        verbose_name="дата рождения",
                    ),
                ),
                (
                    "coffee_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Счётчик выпитого кофе",
                        verbose_name="количество выпитого кофе",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Аватарка",
                        null=True,
                        upload_to=users.models.item_directory_path,
                        verbose_name="изображение",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительное поле",
                "verbose_name_plural": "дополнительные поля",
                "ordering": ("user",),
            },
        ),
    ]
