# Generated by Django 4.2 on 2024-03-17 08:33

from django.db import migrations
import sorl.thumbnail.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={
                'verbose_name': 'дополнительное поле',
                'verbose_name_plural': 'дополнительные поля',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.item_directory_path,
                verbose_name='изображение',
            ),
        ),
    ]
