# Generated by Django 4.2 on 2024-03-20 14:02

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(
                blank=True, null=True, verbose_name='дата рождения'
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coffee_count',
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='количество выпитого кофе',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.item_directory_path,
                verbose_name='изображение',
            ),
        ),
    ]
