# Generated by Django 4.2 on 2024-03-19 14:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.item_directory_path,
                verbose_name='изображение',
            ),
        ),
    ]
