# Generated by Django 4.2 on 2024-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(
                blank=True, null=True, verbose_name='дата рождения'
            ),
        ),
    ]
