# Generated by Django 4.2 on 2024-02-18 16:25

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('catalog', '0001_initial'),
        ('catalog', '0002_alter_category_id_alter_item_id_alter_tag_id'),
        ('catalog', '0003_item_category_item_tags'),
        (
            'catalog',
            '0004_alter_category_id_alter_category_is_published_and_more',
        ),
        ('catalog', '0005_alter_category_options_alter_item_options_and_more'),
        ('catalog', '0006_alter_category_options_alter_item_options_and_more'),
        (
            'catalog',
            '0007_alter_tag_options_alter_category_is_published_and_more',
        ),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='id',
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Дата публикации',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Введите слаг для категории',
                        max_length=200,
                        unique=True,
                        validators=[catalog.models.validator_for_tag_slug],
                        verbose_name='слаг',
                    ),
                ),
                (
                    'weight',
                    models.IntegerField(
                        default=100,
                        help_text='Введите вес',
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name='вес',
                    ),
                ),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='id',
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Дата публикации',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'slug',
                    models.CharField(
                        help_text='Введите слаг для тега',
                        max_length=200,
                        unique=True,
                        validators=[catalog.models.validator_for_tag_slug],
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        help_text='id',
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinLengthValidator(1)
                        ],
                        verbose_name='id',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True,
                        help_text='Дата публикации',
                        verbose_name='опубликовано',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Введите название',
                        max_length=150,
                        unique=True,
                        verbose_name='название',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='Введите сообщение',
                        validators=[catalog.validators.ValidateMustContain],
                        verbose_name='текст',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        help_text='Выберите категорию',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='catalog.category',
                        verbose_name='категория',
                    ),
                ),
                (
                    'tags',
                    models.ManyToManyField(
                        help_text='Выберите тэг',
                        related_name='items',
                        to='catalog.tag',
                        verbose_name='теги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
