# Generated by Django 4.2 on 2024-02-18 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="id",
            ),
        ),
    ]
