# Generated by Django 4.2 on 2024-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_mainimage_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                help_text="будет приведено к размеру 300x300",
                upload_to="gallery_images_item/",
                verbose_name="изображения",
            ),
        ),
        migrations.AlterField(
            model_name="mainimage",
            name="image",
            field=models.ImageField(
                help_text="будет приведено к размеру 300x300",
                upload_to="main_image_items/",
                verbose_name="главное изображение",
            ),
        ),
    ]
