# Generated by Django 4.2 on 2024-02-18 15:29

import catalog.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        (
            "catalog",
            "0004_alter_category_id_alter_category_is_published_and_more",
        ),
        ("catalog", "0005_alter_category_options_alter_item_options_and_more"),
        ("catalog", "0006_alter_category_options_alter_item_options_and_more"),
    ]

    dependencies = [
        ("catalog", "0003_item_category_item_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                help_text="id",
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Дата публикации",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Введите название",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                help_text="Введите слаг для категории",
                max_length=200,
                unique=True,
                validators=[catalog.models.validator_for_tag_slug],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Введите вес",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="Вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="Выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.BigAutoField(
                help_text="id",
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Дата публикации",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="Введите название",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите тэг",
                related_name="items",
                to="catalog.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Введите сообщение",
                validators=[catalog.models.validator_for_item_text],
                verbose_name="Текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                help_text="id",
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="id",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Дата публикации",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Введите название",
                max_length=150,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                help_text="Введите слаг для тэга",
                max_length=200,
                unique=True,
                validators=[catalog.models.validator_for_tag_slug],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "тэг", "verbose_name_plural": "тэги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                help_text="Введите слаг для категории",
                max_length=200,
                unique=True,
                validators=[catalog.models.validator_for_tag_slug],
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Введите вес",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Введите сообщение",
                validators=[catalog.models.validator_for_item_text],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(
                help_text="Введите слаг для тэга",
                max_length=200,
                unique=True,
                validators=[catalog.models.validator_for_tag_slug],
                verbose_name="слаг",
            ),
        ),
    ]
