# Generated by Django 4.2 on 2024-02-26 09:32

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_galleryimage_image_alter_mainimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(
                help_text='Введите сообщение',
                validators=[
                    catalog.validators.ValidateMustContain(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='текст',
            ),
        ),
    ]
