# Generated by Django 4.2 on 2024-03-03 06:40

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(
                help_text='будет приведено к размеру 300x300',
                upload_to=catalog.models.item_directory_path,
                verbose_name='изображения',
            ),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(
                help_text='будет приведено к размеру 300x300',
                upload_to=catalog.models.item_directory_path,
                verbose_name='главное изображение',
            ),
        ),
    ]
