# Generated by Django 4.2 on 2024-03-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='item',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gallery_images',
                related_query_name='gallery_image',
                to='catalog.item',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                related_query_name='item',
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
    ]
