# Generated by Django 4.2 on 2024-02-18 15:37

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'catalog',
            '0004_alter_category_id_alter_category_is_published_and_more_squashed_0006_alter_category_options_alter_item_options_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Дата публикации',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Введите название',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(
                help_text='Выберите категорию',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='catalog.category',
                verbose_name='категория',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Дата публикации',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Введите название',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                help_text='Выберите тэг',
                related_name='items',
                to='catalog.tag',
                verbose_name='теги',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(
                default=True,
                help_text='Дата публикации',
                verbose_name='опубликовано',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Введите название',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(
                help_text='Введите слаг для тега',
                max_length=200,
                unique=True,
                validators=[catalog.models.validator_for_tag_slug],
                verbose_name='слаг',
            ),
        ),
    ]
