# Generated by Django 4.2 on 2024-03-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_galleryimage_item_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name='дата создания'
            ),
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name='последнее изменение'
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(
                default=False, verbose_name='для главной'
            ),
        ),
    ]
