# Generated by Django 4.2 on 2024-03-07 17:18

import catalog.models
import catalog.validators
import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_created_item_updated_alter_item_is_on_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ('name',),
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={
                'ordering': ('name',),
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Введите название, максимальная длинна - 150',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Введите слаг для тэга, максимальная длинна - 200',
                max_length=200,
                verbose_name='слаг',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(
                default=100,
                help_text='Введите вес (от 1 до 32767)',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='вес',
            ),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(
                help_text='Будет приведено к размеру 300x300',
                upload_to=catalog.models.item_directory_path,
                verbose_name='изображения',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(
                help_text='Введите название, максимальная длинна - 150',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(
                help_text='Введите сообщение с содержанием следующих слов: превосходно/роскошно',
                validators=[
                    catalog.validators.ValidateMustContain(
                        'превосходно', 'роскошно'
                    )
                ],
                verbose_name='текст',
            ),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(
                help_text='Будет приведено к размеру 300x300',
                upload_to=catalog.models.item_directory_path,
                verbose_name='главное изображение',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Введите название, максимальная длинна - 150',
                max_length=150,
                unique=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                help_text='Введите слаг для тэга, максимальная длинна - 200',
                max_length=200,
                verbose_name='слаг',
            ),
        ),
    ]
